---

- name: Add OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install php packages
  apt: name={{ item }} state=present
  with_items: php_common_packages

- name: Customize PHP fpm configuration file
  ini_file: dest={{ php_fpm_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini
  notify:
   - restart php-fpm

- name: Customize PHP cli configuration file
  ini_file: dest={{ php_cli_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini

- include: opcache.yml
  tags: php-opcache

- include: xdebug.yml
  tags: php-xdebug

# - include: phpbrew.yml
#   when: php_brew_enable
#   tags: php-brew
#
- name: Enable php modules
  command: php5enmod {{ item }}
  with_items: php_enabled_modules
  notify:
    - restart php-fpm

- name: Disable php modules
  command: php5dismod {{ item }}
  with_items: php_disabled_modules
  notify:
    - restart php-fpm
