# Ansible playbook to create and manage user accounts
---

- hosts: all
  user: root
  tasks:
    - name: Create a bunch of users
      user: name={{item.username}}
            createhome=yes
            state=present
            groups={{item.groups}}
            append=yes
            shell=/bin/zsh
            generate_ssh_key=yes
            ssh_key_bits=2048
            ssh_key_file=.ssh/id_rsa
      with_items: users

    - name: Import key from github
      authorized_key: user={{item.username}} key=https://github.com/{{item.github}}.keys
      with_items: users

    - name: Create blank .zshrc file
      shell: touch /home/{{item.username}}/.zshrc
      args:
        chdir: /home/{{item.username}}
        creates: .zshrc
      with_items: users

    - name: Initialize gitconfig file
      template: src=../templates/gitconfig.j2
                dest=/home/{{item.username}}/.gitconfig
                owner={{item.username}}
                group={{item.username}}
                mode=0644
      with_items: users

    - name: Enable sudo users
      template: src=../templates/sudoer.j2
                dest=/etc/sudoers.d/{{item.username}}
                owner=root
                group=root
                validate='visudo -cf %s'
      with_items: users
